### ISSUE TITLE
Test using exported IETF Trac database

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#19]
Available here: https://github.com/ietf-ribose/trac-svn-db

Maybe a CI action that tests export of the IETF Trac database into offline file.

NOTE: This is a private repository, you can use the `secrets.IETF_RIBOSE_CI_PAT` GitHub token (available in this repo) to access it in CI.

**Comment by ronaldtse** [comment]
The 5 trac databases are available here:
- https://github.com/ietf-ribose/trac-svn-db/tree/main/trac

**Comment by HassanAkbar** [comment]
@ronaldtse do you want me to prioritize this one?

**Comment by ronaldtse** [comment]
@HassanAkbar sure, that would be good validation.

**Comment by HassanAkbar** [comment]
> @HassanAkbar sure, that would be good validation.

@ronaldtse there are a bunch of `.bak` and `.db` files in each `db` directory. 
Can you guide me which files should be used ? 

Also, there are some SQLite Databases as well. 
For example, https://github.com/ietf-ribose/trac-svn-db/tree/main/trac/dmarc/db.
Should we first validate `tractive` with MySQL?  
Do we need add support for SQLite as well as part of this issue and test it with all Databases?

**Comment by ronaldtse** [comment]
@HassanAkbar we only need to test against the “real” database files, ie. Not the bak ones. Indeed these are all SQLite3 databases. We will need to add support for it — MySQL is probably not important for this test.

**Comment by HassanAkbar** [comment]
> @HassanAkbar we only need to test against the “real” database files, ie. Not the bak ones. Indeed these are all SQLite3 databases. We will need to add support for it — MySQL is probably not important for this test.

Perfect 👍 . I will add support for SQLite as well.

**Comment by HassanAkbar** [comment]
@ronaldtse  I [ran a test on 404/3398 issues](https://github.com/hassanakbar4/test_trac_data/issues?q=is%3Aopen+is%3Aissue). It took around 30 mins.
Should we pick small samples for CI action to reduce this time?
What do you recommend?

**Comment by ronaldtse** [comment]
@HassanAkbar sure let's pick samples to reduce CI time.

**Comment by HassanAkbar** [comment]
@ronaldtse 

[Subtickets](https://github.com/ietf-ribose/tractive/blob/a0bbfc6df9acb498eb984a5565e14fd3aef4acd2/lib/tractive/trac.rb#L11) were present in the tractive but there is no database table for it in the imported databases. Do we need support for sub-tickets or should I remove it from the code?

**Comment by ronaldtse** [comment]
@HassanAkbar let's remove Subtickets since they are not a default Trac feature. Thanks.
