### ISSUE TITLE
CI: Create sample Trac database to test against

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#2]
A mock database of Trac information.

**Comment by HassanAkbar** [comment]
@ronaldtse we should support both SQLite3 and mysql2 or a single DB engine here?

**Comment by ronaldtse** [comment]
The current database is in MySQL, so SQLite3 is just a nice to have.

**Comment by ronaldtse** [comment]
This is done in #16

**Comment by HassanAkbar** [comment]
> This is done in #16

Yes @ronaldtse . Closing it
