### ISSUE TITLE
"replying to comment" should link to newly mapped issue

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#24]
<img width="683" alt="Screenshot 2021-08-31 at 5 48 13 PM" src="https://user-images.githubusercontent.com/11865/131481413-79efd0ff-5242-4598-9aae-434ed20f0bff.png">

Should be "Replying to https://github.com/hassanakbar4/test_trac_data/issues/194#issue-983593025:"

**Comment by HassanAkbar** [comment]
@ronaldtse we won't be able to do this if we are using Bulk import API for Github.
Because all comments are created against an issue in a single request.

**Comment by ronaldtse** [comment]
@HassanAkbar let us ask @rjsparks for preference.

@rjsparks we have come to a choice between using the GitHub bulk import API vs GitHub API v3. The considerations right now are:

* Bulk import API: can keep the original time of post/comment, but unable to link between those comments from within a comment (i.e. comment 1 can't semantically quote/link to comment 2)
* API v3: can link comments but all posts/comments will have a creation time of the time of import.

In any case, we have to use a fictitious "migration user" for the migration of such content due to GitHub limitations.

**Comment by rjsparks** [comment]
The comments all point inside the same ticket/issue, and as long as the names labeling who made the comments are preserved, those names and the quoted context will be enough to let us find what was being responded to. Preserving the dates will be more important to understanding the conversation in the ticket than preserving the issue-internal links. If those are the limits of the choices, then what you describe getting from the bulk import API would be more useful than what you are getting from v3.

In case you haven't already explored this:  would it be possible to add the original date as _text_ at the top of the comment? That might change the potential solution space. I don't think the github issues api lets you search comments by date, so having what the v3 api does wouldn't be so bad if the original comment date was available in the text. Fwiw, we don't search _comments_ by date in trac right now, but we do occasionally search tickets by date ranges.

**Comment by rjsparks** [comment]
it is a little sad that neither solution will allow for a search by commenter though. But if that's all that can be done we'll have to live with it. Such searches have not been important to date, but its not hard to imagine a use-case where it would have been a reasonable thing to want to do.

**Comment by ronaldtse** [comment]
> In case you haven't already explored this: would it be possible to add the original date as text at the top of the comment?

It is certainly possible (and reasonable) to do so. I agree that it's rather rare to search comments by date, but if our goal is to be able to migrate as much data to GitHub's data attributes, being able to insert the dates might be an accomplishment.

Actually, there is another possibility to establish links between GitHub comments:

1. First use the Bulk Import API to create those comments
2. Edit those comments to replace old links with GitHub-native links

Admittedly this is a rather poor hack but it might do the job?

**Comment by ronaldtse** [comment]
> it is a little sad that neither solution will allow for a search by commenter though

There exists a long-running GitHub forum thread that is waiting for this functionality, but I suspect that GitHub won't want to allow this possibility to prevent potential abusers importing issues that may not be originally authored by a particular person. (a security issue, in other words)

**Comment by HassanAkbar** [comment]
> > In case you haven't already explored this: would it be possible to add the original date as text at the top of the comment?
> 
> It is certainly possible (and reasonable) to do so. I agree that it's rather rare to search comments by date, but if our goal is to be able to migrate as much data to GitHub's data attributes, being able to insert the dates might be an accomplishment.
> 
> Actually, there is another possibility to establish links between GitHub comments:
> 
> 1. First use the Bulk Import API to create those comments
> 2. Edit those comments to replace old links with GitHub-native links
> 
> Admittedly this is a rather poor hack but it might do the job?

@ronaldtse we are using Bulk import API to create comments now. 
Do we need to use edit API for each comment to replace old links or this is not needed for now?

**Comment by ronaldtse** [comment]
> Do we need to use edit API for each comment to replace old links with GitHub-native links or this is not needed for now?

Yes we will want to do this. Thanks!
