### ISSUE TITLE
Mapping Trac emails to GitHub users

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#26]
We need to decide how we represent people who wrote / commented a ticket:
* emails
* GitHub usernames

Note that not all emails can be mapped to GitHub emails, e.g.
* `henrik@levkowetz.com` maps to `levkowetz`
* `rjsparks@nostrum.com` does not map to `rjsparks`

We could **potentially** automatically map users via the GitHub search interface:
e.g. https://github.com/search?q=rjsparks%40nostrum.com+in%3Aemail&type=Users

But it might work better to have a pre-defined map for consistency.

**Comment by HassanAkbar** [comment]
@ronaldtse 

Currently, we place the mappings in the `config.yaml` file the format is `owner_name_in_trac: github_username`. if the username is correct the issue is created successfully but if the username does not match with the user on GitHub the issue will not be created and there will be an error saying the username is invalid.

What we can do is create a default user on Github and if a mapping does not exist for a user we can use the default user.

**Comment by ronaldtse** [comment]
@HassanAkbar agree with providing a fallback user but in a migration we really want to map to the proper users. In this sense we need to allow the person who runs tractive to build the user map incrementally, ie., 

1. do a local export, 
2. then build the user map from Trac to GitHub, 
3. then allow using that user map when creating the issues on GitHub.

**Comment by rjsparks** [comment]
I was anticipating a manual run of the committing identities from svn through the github api mentioned, and then inspecting the result, adjusting it as necessary. My initial experiments indicated that this would really not require much adjustment.

Mapping all trac committers might be more difficult, but I was anticipating the same activity.

**Comment by ronaldtse** [comment]
@rjsparks we will definitely do a full map for Trac users.

For SVN, do we want to change the emails of the commits? I suspect we don't -- but if that's the case the commits may not link back to a GitHub user, which is understandable since people do change their emails.

**Comment by rjsparks** [comment]
Could you find a concrete example and let us talk through that part of the problem with it?
We do have a good collection of the email addresses for a given person. when they've been active in the IETF, and the majority of the contributors to that SVN repository will be like that.

**Comment by ronaldtse** [comment]
The full user map will be available here: ietf-ribose/svn-github-convert#21

**Comment by ronaldtse** [comment]
Closing, this is done.
