### ISSUE TITLE
Broken badge table

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#28]
This screenshot shows that the "badge table" is not properly migrated. If there is no table, do not create this.

<img width="682" alt="Screenshot 2021-08-31 at 6 43 32 PM" src="https://user-images.githubusercontent.com/11865/131488933-16c43400-0401-468b-bcaf-28d41ba51088.png">

Relevant code:
https://github.com/ietf-ribose/tractive/blob/a0bbfc6df9acb498eb984a5565e14fd3aef4acd2/lib/tractive/migrator.rb#L350-L362

**Comment by ronaldtse** [comment]
And clearly here `github_assignee` is empty, too.

**Comment by ronaldtse** [comment]
This is related to #27.

**Comment by HassanAkbar** [comment]
The badge mapping was missing in the config file that is why the badges were missing in GitHub tickets. Actually, before running the tractive we need to create the config file by running the `tractive --info` command and then adjusting the output accordingly. 

I've mapped the badges and ran it once again [here](https://github.com/hassanakbar4/trac_test_1/issues?q=is%3Aopen+is%3Aissue) is the output. You can see that all the badges are now populating porperly.

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar , confirm this works. Closing.
