### ISSUE TITLE
Rewrite `markdownify` which converts Trac ticket rich-text into Markdown

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#4]
Need to support:

* ticket references
* changeset references
* image references
* links
* etc.

**Comment by ronaldtse** [comment]
Refer to https://github.com/tracboat/tracboat/blob/master/src/tracboat/trac2down.py for a more solid implementation.

**Comment by ronaldtse** [comment]
Other implementations:
* https://gist.github.com/kskmori/3bcd68fa022e635105af285274161dbb
* https://gist.github.com/ismangil/ee015262e373b1d6298be87ff193d92e/revisions

**Comment by HassanAkbar** [comment]
@ronaldtse Here is the list of all the formatting options available in [Trac wiki formatting](https://trac.edgewall.org/wiki/WikiFormatting). I think we should use a gem for the conversion like [Pandoc-ruby](https://github.com/xwmx/pandoc-ruby) so that we won’t miss any case in this conversion.

**Comment by ronaldtse** [comment]
Indeed.

**Comment by HassanAkbar** [comment]
@ronaldtse 
How are we going to handle images? We can't upload images directly to Github. We need to upload the images somewhere first and then add their links to the issues.
Do you have a recommended library for image uploading like S3 etc?

**Comment by ronaldtse** [comment]
While Octokit.rb doesn't support the upload, this article suggests that we can create a repo, commit the images to that repo, and link the images in the comments:
http://www.simplexanswer.com/2019/05/github-api-how-to-upload-a-file/
