### ISSUE TITLE
Issues should not have GitHub Milestone assigned if there was no milestone set in Trac

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#49]
From https://github.com/ietf-svn-conversion/ietfdb-mailarchive/issues

<img width="923" alt="Screenshot 2021-10-18 at 6 10 00 PM" src="https://user-images.githubusercontent.com/11865/137711635-fb34dd36-bf83-4583-a043-22079dbf0a8e.png">

There are two potential cases here, I'm not sure which one:
1. The "(None)" milestone is what we created to hold tickets with no milestones. In this case we should skip assigning the milestone.
2. The "(None)" milestone represents an assigned milestone in Trac, but I think the user would want to skip this type of milestone. Maybe we provide a configuration option to "{milestone-name} => nil"?

**Comment by HassanAkbar** [comment]
@ronaldtse Trac has a milestone named "(None)". 
I imported the same milestone to `Github`. Its currently assigned to all `Github Issue` having milestone "(None)" milestone in the respective Trac Ticket.


<img width="1315" alt="Screenshot 2021-10-18 at 3 21 54 PM" src="https://user-images.githubusercontent.com/5301572/137713656-57d4ee35-d810-49d9-93b7-753922d83318.png">


We have both options available. We can remove it completely from the `Github Issues` or we can rename it in Github.

**Comment by HassanAkbar** [comment]
Actually, this config file is generated by running `tractive -i`.
We can edit/remove anything in the config file before running Ticket Migration.

Removing: the following part in `config.yaml` will taking care of it automatically:
```yaml
"(None)":
  :name: "(None)"
  # ...
```

Given the above info, do we even need a `delete` flag?
We can add desired functionality by just removing the above code block before running the migration.

**Comment by ronaldtse** [comment]
Ah, then removal of that block is fine then. Thanks!
