### ISSUE TITLE
Migrate OptParse to Thor for command-line options

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#6]

**Comment by HassanAkbar** [comment]
@ronaldtse Right now, we have a number God method. 
Should we add a separate task for refactoring and add test cases in that PR?

**Comment by ronaldtse** [comment]
@HassanAkbar what do you mean by "number God method"? Refactoring is certainly a good thing to do in this PR.

**Comment by HassanAkbar** [comment]
> @HassanAkbar what do you mean by "number God method"? Refactoring is certainly a good thing to do in this PR.

Sorry made a typo, I meant `number of God methods`.
Sure thing, I will get that done.

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar !
