### ISSUE TITLE
Implement Trac Wiki migration to GitHub Wiki

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#63]
From @HassanAkbar .

[tracwiki2githubwiki](https://github.com/ggainey/tracwiki2githubwiki) seems to do `Trac -> Github Wiki` migration well. 

* This script copies the text into files with version histories migrated from Trac. We can do this as well.
* This script does not change the formatting of the text (pushes untranslated wiki pages with Trac wiki formatting to Github)
  * We will need to use Tractive's TWF converter to convert into Markdown.
* This script does not migrate attachments.
  * We will need to implement attachment migration.

GitHub Wikis are implemented as a Git repositories:
* The Wiki repo for a `https://github.com/tractive/sample/` is `https://github.com/tractive/sample.wiki.git` or the corresponding SSH version.

This is a [sample](https://github.com/hassanakbar4/foobar/wiki) for the migrated `wikis` for `ietfdb` by @HassanAkbar .

**Comment by HassanAkbar** [comment]
@rjsparks In `ietfdb` there are 2 different wikis named `Sandbox` and `SandBox`, But GitHub does now allow to make 2 different wikis with same name so we need to rename or remove one of these. 

<img width="250" alt="Screenshot 2021-12-08 at 5 28 36 PM" src="https://user-images.githubusercontent.com/5301572/145209069-46470399-c667-4c89-b977-4016b71a5f12.png">

What do you suggest we should do here?
