### ISSUE TITLE
Wiki conversion: Convert WikiMedia code blocks into Markdown

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#74]
It looks like things that should be `treated as code` appear as [source:this is not code] instead. E.g., https://github.com/ietf-svn-conversion/ietfdb/wiki/CodeRepository in the second paragraph of the top section

_Originally posted by @jennifer-richards in https://github.com/ietf-ribose/github-migration-project/issues/12#issuecomment-996897541_

**Comment by HassanAkbar** [comment]
For `[source:branch/]`, `[source:tags/]`, and `[source:trunk/]` we can map them to [`branch list page`](https://github.com/ietf-svn-conversion/ietfdb/branches/all), [`tags list page`](https://github.com/ietf-svn-conversion/ietfdb/tags), and [`main branch`](https://github.com/ietf-svn-conversion/ietfdb) in Github respectively.

But there are also occurrences with filters that are not available in Github.
For example:
- `[source:tags/?order=date&desc=1 tags/]`

@rjsparks What do you suggest we should do to translate these types of links in `Github`?

**Comment by rjsparks** [comment]
At the very least the above should map to `tags list page`. If there's a way to honor the order argument, please do so. Ignore the desc (and any other arguments that are really just signals to trac's rendering engine).
